import type { Metadata } from "next";
import NavCategories from "@/components/NavCategories";
import Link from "next/link";
import CartIcon from "./../../components/CartIcon";
import UserIcon from "@/components/UserIcon";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid grid-rows-[80px,calc(100vh-50px)] h-screen max-h-screen min-h-screen max-w-full">
        <Header />
        <main className="relative h-full min-h-screen flex gap-5  ">
          <div className="w-1/4 relative hidden md:flex max-h-screen ">
            <NavCategories />
          </div>
          <div className="w-full h-full bg-black flex">
            {children}
          </div>
          <div className="absolute right-3 top-2 mt-2 flex gap-2 items-start">
            <CartIcon />
            <UserIcon />
          </div>
        </main>
        <footer className="flex py-2 items-center justify-center text-white bg-blue-900">
          Hecho por hAver webs
        </footer>
      </body>
    </html>
  );
}
